language: node_js
node_js:
  - 10
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv -in client-secret.json.enc -out client-secret.json -d
  - docker build -t lemillion/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true lemillion/docker-react npm run test
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: docker-react-278610
  on:
    branch: master
