language: node_js
node_js:
  - 10
services:
  - docker
before_install:
  - docker build -t lemillion/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true lemillion/docker-react npm run test
# deploy:
#   provider: gae
#   skip_cleanup: true
#   keyfile: client-secret.json
#   project: docker-react
#   on:
#     branch: master
